### ISSUE TITLE
Cyprus Compatibility

### ISSUE THREAD

**Issue by ng-druid** [marmelab/greenframe-cli#17]
Playwright is wonderful but many organizations including [my own](https://www.cylitix.com/) have written all our tests using [Cyprus](https://www.cypress.io/). It would be ideal to at a flip of the switch run green frame using Cyprus where migration to Playwright is unrealistic and/or political. It is difficult for me and I would suppose others to sell the idea of measuring carbon emissions to our teams let alone requiring migration to Playwright. Framework agnostic or at least support of more popular systems like Cyprus would make for a much easier sell and transition to greening software.

Side Note: [TestCafe](https://testcafe.io/) is also a very well known test ecosystem. I'm sure they would love to have something like this on their cloud and part of their [enterprise studio solution](https://www.devexpress.com/products/testcafestudio/).

**Comment by fzaninotto** [comment]
Hi, and thanks for your suggestion.

We've used Cypress in the past instead of Plawright. The reason we made the switch is that Cypress does have a significant footprint, which alters  the browser container measurement. The playwright footprint accounts for less than 3% of the browser container footprint in our tests.
